repos:
-   repo: https://github.com/ambv/black
    rev: 21.4b2
    hooks:
    - id: black
      language_version: python3.8
      args: ["--line-length=110"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.1'
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]
      args: ["--show-source", "--max-line-len=110", "--ignore=D1,W503,E201,E203"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
    - id: mypy
      args: ["--follow-imports=skip", "--check-untyped-defs", "--ignore-missing-imports"]
